name: Run Unit Tests

on:
  push:
    branches: [ feature/laboratorio-testing-opcional ]
  pull_request:
    branches: [ feature/laboratorio-testing-opcional ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run unit tests with Vitest
        run: npm run test
