name: Run Unit Tests

on:
  push:
    branches: [feature/laboratorio-testing-opcional]
    paths:
      - 'entrega-tests/**'
  pull_request:
    branches: [feature/laboratorio-testing-opcional]
    paths:
      - 'entrega-tests/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Run unit tests with Vitest
        run: npm run test
